# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Package version

on:
  push:

#env:
#  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  package-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

#      - name: Set up Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: 16.x

      - name: Get last publish version
        id: package_version
        run: current-version=$(curl -s https://${TOKEN}@raw.githubusercontent.com/happywait/hw-lib-front.core.api/${BRANCH}/package.json | jq -r '.version')
        env:
          TOKEN: ${{ secrets.CI_TOKEN }}
          BRANCH: master

      - name: Echo current version
        run: echo ${{ steps.package_version.outputs.current-version}}
#
#      - name: Bump package version
#        uses: "phips28/gh-action-bump-version@master"
#        with:
#          tag-prefix: ''
#        env:
#          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

      #      - name: Push to protected branch
      #        uses: CasperWA/push-protected@v2
      #        with:
      #          token: ${{ secrets.CI_TOKEN }}
      #          branch: main
      #          unprotect_reviews: true

      #      - name: Publish package
      #        run: npm publish

      #       Removed because committing to master not permitted, workaround not found
      #      - name: "Automated Version Bump"
      #        uses: "phips28/gh-action-bump-version@master"
      #        with:
      #          tag-prefix: ''
      #        env:
      #          NPM_TOKEN: ${{secrets.CI_TOKEN}}
