# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Package version

on:
  push:

#env:
#  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  package-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

#      - name: Set up Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: 16.x

      - name: Get last version of master
        id: master_version
        run: |
          echo ::set-output name=version::$(curl -s https://${TOKEN}@raw.githubusercontent.com/mdeoliveira-hw/gh-push-protected/${BRANCH}/package.json | jq -r '.version')
        env:
          TOKEN: ${{ secrets.CI_TOKEN }}
          BRANCH: master

      - name: Get version of branch
        id: branch_version
        run: echo ::set-output name=version::$(cat package.json | jq -r '.version')

      - name: Echo master version
        run: echo ${{ steps.master_version.outputs.version }}

      - name: Echo branch version
        run: echo ${{ steps.branch_version.outputs.version }}

#      - name: Reset version
#        if: ${{ steps.branch_version.outputs.version != steps.master_version.outputs.version }}
#        uses: jossef/action-set-json-field@v2
#        with:
#          file: package.json
#          field: version
#          value: ${{ steps.master_version.outputs.version }}
#
#      - name: Bump package version
#        uses: "phips28/gh-action-bump-version@master"
#        with:
#          tag-prefix: ''
#        env:
#          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

      #      - name: Push to protected branch
      #        uses: CasperWA/push-protected@v2
      #        with:
      #          token: ${{ secrets.CI_TOKEN }}
      #          branch: main
      #          unprotect_reviews: true

      #      - name: Publish package
      #        run: npm publish

      #       Removed because committing to master not permitted, workaround not found
      #      - name: "Automated Version Bump"
      #        uses: "phips28/gh-action-bump-version@master"
      #        with:
      #          tag-prefix: ''
      #        env:
      #          NPM_TOKEN: ${{secrets.CI_TOKEN}}
